create table if not exists clans (
  tag text primary key,
  data jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists players (
  tag text primary key,
  clan_tag text not null,
  name text not null,
  role text,
  town_hall_level int,
  trophies int,
  donations int,
  donations_received int,
  attack_wins int,
  defense_wins int,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists player_snapshots (
  id bigint generated by default as identity primary key,
  player_tag text not null,
  clan_tag text not null,
  captured_at timestamptz not null default now(),
  data jsonb not null
);
create index if not exists player_snapshots_player_time_idx on player_snapshots(player_tag, captured_at desc);

create table if not exists wars (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  war_key text not null unique,
  state text,
  start_time timestamptz,
  end_time timestamptz,
  data jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists wars_clan_time_idx on wars(clan_tag, end_time desc);

create table if not exists war_participants (
  id bigint generated by default as identity primary key,
  war_key text not null,
  clan_tag text not null,
  player_tag text not null,
  player_name text,
  team text not null,
  map_position int,
  town_hall_level int,
  attacks_used int not null default 0,
  attacks_available int not null default 0,
  stars int not null default 0,
  destruction double precision not null default 0,
  data jsonb not null,
  unique(war_key, team, player_tag)
);
create index if not exists war_participants_war_idx on war_participants(war_key);
create index if not exists war_participants_player_idx on war_participants(player_tag);

create table if not exists war_attacks (
  id bigint generated by default as identity primary key,
  war_key text not null,
  clan_tag text not null,
  attacker_tag text not null,
  attacker_name text,
  defender_tag text not null,
  defender_name text,
  attacker_team text not null,
  order_no int,
  stars int,
  destruction double precision,
  duration int,
  data jsonb not null,
  unique(war_key, attacker_tag, defender_tag, order_no)
);
create index if not exists war_attacks_war_idx on war_attacks(war_key, order_no);
create index if not exists war_attacks_attacker_idx on war_attacks(attacker_tag);

create table if not exists cwl_seasons (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  season_key text not null unique,
  data jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists cwl_rounds (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  season_key text not null,
  round_no int not null,
  opponent_tag text,
  opponent_name text,
  state text,
  data jsonb not null,
  unique(season_key, round_no)
);

create table if not exists capital_raids (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  season_key text not null unique,
  data jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists sync_runs (
  id bigint generated by default as identity primary key,
  job text not null,
  status text not null,
  details jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

-- Protect the AI/Discord runtime from writes.
-- Run this section in the dedicated Supabase project after creating the tables.
-- The public/anon role receives SELECT only; writes remain available to service_role.

alter table clans enable row level security;
alter table players enable row level security;
alter table player_snapshots enable row level security;
alter table wars enable row level security;
alter table war_participants enable row level security;
alter table war_attacks enable row level security;
alter table cwl_seasons enable row level security;
alter table cwl_rounds enable row level security;
alter table capital_raids enable row level security;

create policy "ai read clans" on clans for select to anon using (true);
create policy "ai read players" on players for select to anon using (true);
create policy "ai read snapshots" on player_snapshots for select to anon using (true);
create policy "ai read wars" on wars for select to anon using (true);
create policy "ai read war participants" on war_participants for select to anon using (true);
create policy "ai read war attacks" on war_attacks for select to anon using (true);
create policy "ai read cwl seasons" on cwl_seasons for select to anon using (true);
create policy "ai read cwl rounds" on cwl_rounds for select to anon using (true);
create policy "ai read capital raids" on capital_raids for select to anon using (true);
